// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1709745849);
user_pref("browser.search.region", "KH");
user_pref("calendar.caldav.googleResync", 1709745847);
user_pref("calendar.list.sortOrder", "61db7562-6514-4ddc-af4e-c979f6466db7");
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.calendar-main-default", true);
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.calendar-main-in-composite", true);
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.disabled", true);
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.name", "Home");
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.type", "storage");
user_pref("calendar.registry.61db7562-6514-4ddc-af4e-c979f6466db7.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/New_York");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1709745847);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230214184313");
user_pref("extensions.lastAppVersion", "102.8.0");
user_pref("extensions.lastPlatformVersion", "102.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"ac5cd1d6-4fd1-4a93-9708-aa149c74753d\",\"google@search.mozilla.org\":\"87bcbec2-9c1b-4242-bbb4-7cf01f43f6a7\",\"ddg@search.mozilla.org\":\"565117d9-7076-4627-9050-1d77801292be\",\"amazondotcom@search.mozilla.org\":\"3e3aa661-9cb4-45d8-91b6-fa8ecdcb81d5\",\"wikipedia@search.mozilla.org\":\"bfd630ed-e244-4925-8091-85fed8d9de05\",\"bing@search.mozilla.org\":\"38ffe68e-20e8-4d90-9a9f-ec4dc172c0ed\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "5a1e2dfa-1781-4e8d-a29b-45478cf926f");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.8.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "cf792ab9-18de-4169-bd95-37cedd7df448");
user_pref("toolkit.telemetry.previousBuildID", "20230214184313");
